spring.application.name=jobhunter

#config database
###
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/springrestjob?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true&connectionCollation=utf8mb4_unicode_ci&autoReconnect=true
spring.datasource.username=root
spring.datasource.password=0000
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true
###

###
#config jwt
cdweb.jwt.base64-secret=TRrx3ZoD9xgevlM73MU8/ay9VO+8RJ7NjvFh5Ab0xoTsKzuPYwCOKDZugGYsVxroYRfP94DH6jBxBhFyBPaQQQ==
#expiration : 1 day (seconds = 24 * 60 * 60)
# 100 days
cdweb.jwt.access-token-validity-in-seconds=8640000
cdweb.jwt.refresh-token-validity-in-seconds=8640000
#
###

#config upload file
###
#default = 1MB
spring.servlet.multipart.max-file-size=50MB

#default = 10 MB (form data)
spring.servlet.multipart.max-request-size=50MB

#base path
#cdweb.upload-file.base-uri=file:///D:/1.Udemy/Backend/4.%20Java%20Spring%20Restful/upload/
cdweb.upload-file.base-uri=file:///E:/CDWed/upload/
###

###
#config pagination
#start page = 1
spring.data.web.pageable.one-indexed-parameters=true

###
#

###
#config email with Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587

#thay email c?a b?n vào ?ây
spring.mail.username=tranthanhtri0147@gmail.com

#thay app password c?a ban vao day
spring.mail.password=cucgxlreicrbsrlv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
###
#